<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="21" passed="14" failed="7" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Learn SQL in Practical + Database Testing from Scratch]]>
    </line>
    <line>
      <![CDATA[Learn JMETER from Scratch - (Performance + Load) Testing Tool]]>
    </line>
    <line>
      <![CDATA[QA Expert Course :Software Testing + Bugzilla + SQL + Agile]]>
    </line>
    <line>
      <![CDATA[Master Selenium Automation in simple Python Language]]>
    </line>
    <line>
      <![CDATA[Alex]]>
    </line>
    <line>
      <![CDATA[Ben]]>
    </line>
    <line>
      <![CDATA[Dwayne]]>
    </line>
    <line>
      <![CDATA[Ivory]]>
    </line>
    <line>
      <![CDATA[Jack]]>
    </line>
    <line>
      <![CDATA[Joe]]>
    </line>
    <line>
      <![CDATA[Raymond]]>
    </line>
    <line>
      <![CDATA[Ronaldo]]>
    </line>
    <line>
      <![CDATA[His mentorship program is most after in the software testing community with long waiting period.]]>
    </line>
  </reporter-output>
  <suite started-at="2022-10-12T14:57:42 ART" name="Stori-QA-Automation-Challenge" finished-at="2022-10-12T14:58:11 ART" duration-ms="29139">
    <groups>
    </groups>
    <test started-at="2022-10-12T14:57:42 ART" name="Tests" finished-at="2022-10-12T14:58:11 ART" duration-ms="29139">
      <class name="testSuit.testCases.HomePageTest">
        <test-method is-config="true" signature="beforeAll(java.lang.String)[pri:0, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:57:43 ART" name="beforeAll" finished-at="2022-10-12T14:57:46 ART" duration-ms="3825" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeAll -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:57:46 ART" name="beforeTest" finished-at="2022-10-12T14:57:56 ART" duration-ms="9609" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="loadPageUrlSuccessful()[pri:1, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:57:56 ART" name="loadPageUrlSuccessful" finished-at="2022-10-12T14:57:56 ART" duration-ms="334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadPageUrlSuccessful -->
        <test-method signature="suggestionCountries()[pri:2, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:57:57 ART" name="suggestionCountries" finished-at="2022-10-12T14:57:57 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suggestionCountries -->
        <test-method signature="dropDownOptions()[pri:3, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:57:57 ART" name="dropDownOptions" finished-at="2022-10-12T14:57:58 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dropDownOptions -->
        <test-method signature="windowsExampleLoadSuccessful()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:57:58 ART" name="windowsExampleLoadSuccessful" finished-at="2022-10-12T14:58:03 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="5455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleLoadSuccessful -->
        <test-method signature="windowsExampleTextForInDepth()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:03 ART" name="windowsExampleTextForInDepth" finished-at="2022-10-12T14:58:04 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="35" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Top class material designed on all courses for making you better in depth understanding of the concepts taught in the lectures.] but found [Top class material designed on all courses for making you better indepth understanding of the concepts taught in the lectures]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Top class material designed on all courses for making you better in depth understanding of the concepts taught in the lectures.] but found [Top class material designed on all courses for making you better indepth understanding of the concepts taught in the lectures]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testSuit.testCases.HomePageTest.windowsExampleTextForInDepth(HomePageTest.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTextForInDepth -->
        <test-method signature="windowsExampleTextForLifeTime()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:04 ART" name="windowsExampleTextForLifeTime" finished-at="2022-10-12T14:58:04 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="22" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [We are happy to help you on any query in the course you are enrolled in. Trainer will reach out to you personally once you sign up with the course.] but found [We are happy to help you on any query in the course you are enrolled in.Trainer will reach out to you personally once you signup with the course]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [We are happy to help you on any query in the course you are enrolled in. Trainer will reach out to you personally once you sign up with the course.] but found [We are happy to help you on any query in the course you are enrolled in.Trainer will reach out to you personally once you signup with the course]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testSuit.testCases.HomePageTest.windowsExampleTextForLifeTime(HomePageTest.java:154)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTextForLifeTime -->
        <test-method signature="windowsExampleTextForResumePreparation()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:04 ART" name="windowsExampleTextForResumePreparation" finished-at="2022-10-12T14:58:04 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="27" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [We will help you in preparing the resume and provide good number of Interview questions once you have completed the entire course.] but found [We will help you in preparing the resume and provide good number of Interview questions once you have complete the entire course.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [We will help you in preparing the resume and provide good number of Interview questions once you have completed the entire course.] but found [We will help you in preparing the resume and provide good number of Interview questions once you have complete the entire course.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testSuit.testCases.HomePageTest.windowsExampleTextForResumePreparation(HomePageTest.java:163)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTextForResumePreparation -->
        <test-method signature="windowsExampleTextForSelfPeace()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:04 ART" name="windowsExampleTextForSelfPeace" finished-at="2022-10-12T14:58:04 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [You can access the videos on 24* 7 for Lifetime. You can access the videos in iPad/Mobile too.] but found [You can access the videos on 24* 7 for Life time. You can access the videos in IPad/Mobile too.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [You can access the videos on 24* 7 for Lifetime. You can access the videos in iPad/Mobile too.] but found [You can access the videos on 24* 7 for Life time. You can access the videos in IPad/Mobile too.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testSuit.testCases.HomePageTest.windowsExampleTextForSelfPeace(HomePageTest.java:137)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTextForSelfPeace -->
        <test-method signature="windowsExampleTitle30DayMoneyBack()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:04 ART" name="windowsExampleTitle30DayMoneyBack" finished-at="2022-10-12T14:58:04 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTitle30DayMoneyBack -->
        <test-method signature="windowsExampleTitleInDepth()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:05 ART" name="windowsExampleTitleInDepth" finished-at="2022-10-12T14:58:05 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTitleInDepth -->
        <test-method signature="windowsExampleTitleLifeTime()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:05 ART" name="windowsExampleTitleLifeTime" finished-at="2022-10-12T14:58:05 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [LIFETIME INSTRUCTOR SUPPORT] but found [LIFE TIME INSTRUCTOR SUPPORT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [LIFETIME INSTRUCTOR SUPPORT] but found [LIFE TIME INSTRUCTOR SUPPORT]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testSuit.testCases.HomePageTest.windowsExampleTitleLifeTime(HomePageTest.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTitleLifeTime -->
        <test-method signature="windowsExampleTitleResumePreparation()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:05 ART" name="windowsExampleTitleResumePreparation" finished-at="2022-10-12T14:58:05 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTitleResumePreparation -->
        <test-method signature="windowsExampleTitleSelfPaced()[pri:4, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:05 ART" name="windowsExampleTitleSelfPaced" finished-at="2022-10-12T14:58:05 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTitleSelfPaced -->
        <test-method signature="windowsExampleTextFor30DayMoney()[pri:5, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:05 ART" name="windowsExampleTextFor30DayMoney" finished-at="2022-10-12T14:58:06 ART" depends-on-methods="testSuit.testCases.HomePageTest.windowsExampleLoadSuccessful" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsExampleTextFor30DayMoney -->
        <test-method signature="windowsTabExampleLoadSuccessful()[pri:5, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:06 ART" name="windowsTabExampleLoadSuccessful" finished-at="2022-10-12T14:58:07 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="1704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsTabExampleLoadSuccessful -->
        <test-method signature="windowsTabExampleViewAllCoursesButton()[pri:5, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:08 ART" name="windowsTabExampleViewAllCoursesButton" finished-at="2022-10-12T14:58:09 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="1008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windowsTabExampleViewAllCoursesButton -->
        <test-method signature="switchToAlert()[pri:6, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:09 ART" name="switchToAlert" finished-at="2022-10-12T14:58:09 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="166" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hello Stori Card, Are you sure you want to confirm?] but found [Hello Stori Card, share this practice page and share your knowledge]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hello Stori Card, Are you sure you want to confirm?] but found [Hello Stori Card, share this practice page and share your knowledge]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testSuit.testCases.HomePageTest.switchToAlert(HomePageTest.java:207)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchToAlert -->
        <test-method signature="switchToAlertAndAccept()[pri:7, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:09 ART" name="switchToAlertAndAccept" finished-at="2022-10-12T14:58:09 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="7" status="FAIL">
          <exception class="org.openqa.selenium.NoAlertPresentException">
            <message>
              <![CDATA[no such alert
  (Session info: chrome=105.0.5195.127)
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ab10d928796cfe85a2b39dbe648f668f, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.127, chrome: {chromedriverVersion: 105.0.5195.52 (412c95e51883..., userDataDir: C:\Users\nesto\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:62747}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62747/devtoo..., se:cdpVersion: 105.0.5195.127, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ab10d928796cfe85a2b39dbe648f668f]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoAlertPresentException: no such alert
  (Session info: chrome=105.0.5195.127)
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [ab10d928796cfe85a2b39dbe648f668f, getAlertText {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 105.0.5195.127, chrome: {chromedriverVersion: 105.0.5195.52 (412c95e51883..., userDataDir: C:\Users\nesto\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:62747}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:62747/devtoo..., se:cdpVersion: 105.0.5195.127, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: ab10d928796cfe85a2b39dbe648f668f
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:606)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1084)
at testSuit.testCases.HomePageTest.switchToAlertAndAccept(HomePageTest.java:215)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoAlertPresentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- switchToAlertAndAccept -->
        <test-method signature="printCoursesByPrice()[pri:8, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:09 ART" name="printCoursesByPrice" finished-at="2022-10-12T14:58:10 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="420" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Learn SQL in Practical + Database Testing from Scratch]]>
            </line>
            <line>
              <![CDATA[Learn JMETER from Scratch - (Performance + Load) Testing Tool]]>
            </line>
            <line>
              <![CDATA[QA Expert Course :Software Testing + Bugzilla + SQL + Agile]]>
            </line>
            <line>
              <![CDATA[Master Selenium Automation in simple Python Language]]>
            </line>
          </reporter-output>
        </test-method> <!-- printCoursesByPrice -->
        <test-method signature="printEngineerNames()[pri:8, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:10 ART" name="printEngineerNames" finished-at="2022-10-12T14:58:10 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="278" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Alex]]>
            </line>
            <line>
              <![CDATA[Ben]]>
            </line>
            <line>
              <![CDATA[Dwayne]]>
            </line>
            <line>
              <![CDATA[Ivory]]>
            </line>
            <line>
              <![CDATA[Jack]]>
            </line>
            <line>
              <![CDATA[Joe]]>
            </line>
            <line>
              <![CDATA[Raymond]]>
            </line>
            <line>
              <![CDATA[Ronaldo]]>
            </line>
          </reporter-output>
        </test-method> <!-- printEngineerNames -->
        <test-method signature="textMentorshipParagraph()[pri:8, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:11 ART" name="textMentorshipParagraph" finished-at="2022-10-12T14:58:11 ART" depends-on-methods="testSuit.testCases.HomePageTest.loadPageUrlSuccessful" duration-ms="50" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[His mentorship program is most after in the software testing community with long waiting period.]]>
            </line>
          </reporter-output>
        </test-method> <!-- textMentorshipParagraph -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:testSuit.testCases.HomePageTest@3b69e7d1]" started-at="2022-10-12T14:58:11 ART" name="afterTest" finished-at="2022-10-12T14:58:11 ART" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testSuit.testCases.HomePageTest -->
    </test> <!-- Tests -->
  </suite> <!-- Stori-QA-Automation-Challenge -->
</testng-results>
